"""Turn a Google Fonts css2 response into self-hosted, de-duplicated woff2 subsets.

Driven by internal/webui/fonts.sh, which fetches the stylesheet and points GFONTS_CSS at
it. Kept separate from the shell script because the de-duplication is the whole point and
it is not expressible in shell without being unreadable.

All three families are variable fonts: Google serves ONE file per (family, subset) and
references it from every weight. Naively saving one file per @font-face rule stores the
same bytes four times -- 820K instead of 232K. So files are keyed by content hash and
named for the family and subset, never the weight.
"""

import hashlib
import os
import re
import shutil
import urllib.request

KEEP = {"latin", "latin-ext"}
OUT = "internal/webui/assets/static/fonts"
CSS = "internal/webui/assets/static/fonts.css"

HEADER = """/* Self-hosted subsets of the two families armband.css declares.
 *
 * HANDOFF.md section 6 requires this: there is no network in an embedded webview, and
 * these Google families were the single biggest first-paint cost. Serving them from the
 * binary also makes the page honest about being a local tool.
 *
 * Only latin and latin-ext ship. latin-ext is NOT optional -- player names carry it, and
 * this project has already paid once for treating names as ASCII (see the rune-width fix
 * in internal/present). Kadioglu's dotless i, Odegaard's slashed o and Guehi's circumflex
 * all live in latin-ext. Each face keeps its unicode-range, so a browser fetches only the
 * subsets a page actually needs.
 *
 * Both families are VARIABLE fonts: Google serves one file per (family, subset) and
 * reuses it for every weight. The weights below therefore point at the same file on
 * purpose -- that is not a copy-paste error, and de-duplicating it took this directory
 * from 820K to 232K. Do not "fix" it by fetching one file per weight.
 *
 * Plus Jakarta Sans (the third family, --display) was dropped 2026-08-27: it cost 27,348
 * bytes and one request for headings only, and the owner ruled speed over that face --
 * --display now points at Inter (armband.css). See that change's commit for what it costs
 * visually.
 *
 * Generated by internal/webui/fonts.sh. Do not edit by hand.
 */
"""


def main() -> None:
    src = open(os.environ["GFONTS_CSS"], encoding="utf-8").read()
    blocks = re.findall(r"/\* ([a-z0-9-]+) \*/\s*(@font-face \{.*?\})", src, re.S)
    if not blocks:
        raise SystemExit("no @font-face blocks parsed -- did the css2 response change shape?")

    shutil.rmtree(OUT, ignore_errors=True)
    os.makedirs(OUT, exist_ok=True)

    bycontent: dict[str, str] = {}
    faces = []
    for subset, block in blocks:
        if subset not in KEEP:
            continue
        family = re.search(r"font-family: '([^']+)'", block).group(1)
        weight = int(re.search(r"font-weight: (\d+)", block).group(1))
        url = re.search(r"url\((https://[^)]+\.woff2)\)", block).group(1)

        req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
        data = urllib.request.urlopen(req, timeout=30).read()
        digest = hashlib.sha256(data).hexdigest()
        if digest not in bycontent:
            name = "%s-%s.woff2" % (family.lower().replace(" ", "-"), subset)
            with open(os.path.join(OUT, name), "wb") as f:
                f.write(data)
            bycontent[digest] = name
        name = bycontent[digest]
        faces.append((subset, family, weight, block.replace(url, "fonts/" + name)))

    faces.sort(key=lambda f: (f[1], f[2], f[0]))

    out = [HEADER]
    for subset, family, weight, block in faces:
        out.append("/* %s %d - %s */" % (family, weight, subset))
        out.append(block)
        out.append("")
    with open(CSS, "w", encoding="utf-8") as f:
        f.write("\n".join(out))

    print("%d faces over %d files" % (len(faces), len(bycontent)))


if __name__ == "__main__":
    main()
