package webui_test

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"armband/internal/viewmodel"
)

// The state fixtures the visual suite renders.
//
// # Why the screenshots are NOT taken against the model
//
// They were, and it was the wrong design. A golden generated by running the optimiser over
// a committed capture is a picture of one gameweek's answer, so it tests GW1 and nothing
// else — and there is no way to widen it, because the squad changes every week and the
// prices change even when the squad does not. Locking the squad does not save it. Every
// model change would churn nine images, and a reviewer would learn to run -update without
// looking, which is the moment the suite stops being a gate.
//
// A screenshot can only meaningfully assert LAYOUT: that a card does not overlap its
// neighbour, that a strip does not collapse at 390px, that a colour token has not gone the
// wrong way, that a panel is not empty. None of that is a question about football.
//
// So the fixtures below are fixed documents, committed as JSON, and the browser is served
// them directly. A golden now changes when the layout changes and at no other time. The
// question the old design was trying to answer — does the page draw what the model says —
// is a different test, lives in cmd/armband, and asserts a RELATION rather than a picture,
// so it holds in any gameweek.
//
// The second gain is coverage. A fixture can be any state, including ones the live data
// will not produce on demand: a blank gameweek, a ruled-out player, an empty market, a
// squad in an illegal shape. Those are exactly the layouts most likely to be broken and
// least likely to be looked at.

// fixtureNames are the committed documents under testdata/state. Each is rendered at both
// viewports unless the shot list says otherwise.
var fixtureNames = []string{
	"gameweek-one",   // an ordinary pre-season state, generated from a real run
	"edges",          // the states real data will not hand you on demand
	"import-offered", // the team-ID import affordance offered, from GW2 onward
	// The same state with an entry already on record. Derived from import-offered by
	// setting one field, because that one field IS the change under test: an entry turns
	// #squadsource from an offer into a provenance line carrying "Change team". Holding
	// everything else identical is what makes a diff between the two shots readable.
	"import-imported",
	// A fixture that reaches the third headline in renderNewsNudge, the rotation-risk nudge.
	// No flagged players, one rotation-risk player with no news: derived from gameweek-one
	// by changing Calvert-Lewin's role to "rotation risk".
	"rotation-risk",
	// The transfer bar/panel's three states, each derived from import-imported by adding
	// State.Transfers -- everything else held identical, the same discipline
	// import-imported itself follows against import-offered. See visual_test.go's shot
	// list for what each one is for.
	"import-transfers-none",  // imported, nothing changed since: bar shows "1 free", panel hidden
	"import-transfers-two",   // two changes made, one free: bar shows the −4, panel shows two rows
	"import-transfers-stale", // baseline_stale: the re-import sentence, count and cost withheld
	// A past, FINISHED gameweek on the rail, and its result selected on load (see
	// visual_test.go's shot list, /app#results-1). Derived from import-imported by moving
	// `now` past GW1's deadline, marking GW1 closed/GW2 current, and borrowing GW1's own
	// results block from gameweek-one -- forced to result_state "final" (every
	// match_status "finished") so the shot exercises the settled case a reader actually
	// clicks back to, not the mid-match one gameweek-one's own shots already cover.
	"import-past-result",
	// State 2 (§3.2 of the wildcard design): a gameweek the competition does not
	// allow either chip in yet. Derived from gameweek-one by replacing
	// chip_teams with gameweek 1's own real answer -- both teams nil, both
	// *_unavailable sentences set -- rather than gameweek-one's own gameweek-2
	// chip_teams, which IS available. See TestWriteTheWildcardFixtures.
	"chip-unavailable",
}

// loadState reads one fixture and fails loudly if it does not decode into the contract.
//
// Decoding rather than serving the bytes blind is the point: when a field is added,
// renamed or retyped in internal/viewmodel, this fails on the fixture that no longer fits,
// which is a far better signal than a screenshot quietly losing a panel.
func loadState(t *testing.T, name string) viewmodel.State {
	t.Helper()
	path := filepath.Join("testdata", "state", name+".json")
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading the state fixture %s: %v", name, err)
	}
	var st viewmodel.State
	dec := json.NewDecoder(bytes.NewReader(raw))
	// Unknown fields are an error. A fixture carrying a field the contract dropped is a
	// fixture nobody updated, and it would otherwise render fine and assert nothing.
	dec.DisallowUnknownFields()
	if err := dec.Decode(&st); err != nil {
		t.Fatalf("the state fixture %s no longer fits viewmodel.State: %v\n"+
			"The contract changed and the fixture did not. Regenerate it with\n"+
			"  go test ./cmd/armband/ -run TestWriteTheStateFixture -update", name, err)
	}
	return st
}

func TestEveryStateFixtureFitsTheContract(t *testing.T) {
	for _, name := range fixtureNames {
		st := loadState(t, name)
		if len(st.Squad.Players) == 0 {
			t.Errorf("%s carries no players; it would screenshot an empty pitch and pass", name)
		}
	}
}
