#!/usr/bin/env python3
"""Refuse NEW complexity above the threshold. Existing offenders are grandfathered.

    python3 scripts/complexity-ratchet.py                 # check
    python3 scripts/complexity-ratchet.py --update-baseline
    python3 scripts/complexity-ratchet.py --selftest      # prove it can fail

# Why a ratchet and not a threshold

76 functions in this repo exceed complexity 15; 4 exceed 50. A global threshold
has only two settings and both are useless. Set it above the worst (65) and it can
never fire — an unfalsified guard, which is the failure class this project spent
2026-08-27 closing. Set it below and every unrelated pull request is blocked until
someone lowers it, which is how a gate gets deleted.

So the baseline records what exists, and the gate is on CHANGE: a function may not
be ADDED above the threshold, and an existing one may not get WORSE. Cleaning up
the grandfathered list is separate work, deliberately — the ratchet exists so that
work is optional rather than a precondition for shipping anything else.

⚠️ The baseline is a FLOOR, not a target. Lowering an entry is always allowed and
never needs the file updated: `--update-baseline` is only for when the honest
answer is that a function legitimately grew.

# What it does NOT do

⚠️ Complexity is not correctness. `Simulate` at 65 is heavily tested and
deterministic; `agent.searchPlayers` at 44 sits in the least-covered package in
the repo, behind an untrusted-input boundary. This tool cannot tell those apart
and does not try. It stops the number rising; judging which offenders matter is
the work it defers.
"""
import argparse, os, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASELINE = os.path.join(ROOT, "stats", "complexity-baseline.txt")
THRESHOLD = 15


def measure(root=ROOT):
    files = subprocess.run(
        ["sh", "-c", "find . -name '*.go' -not -name '*_test.go' -not -path './.git/*'"],
        cwd=root, capture_output=True, text=True).stdout.split()
    if not files:
        return {}
    out = subprocess.run(["gocyclo", "-over", str(THRESHOLD)] + files,
                         cwd=root, capture_output=True, text=True)
    if out.returncode not in (0, 1):
        sys.exit(f"gocyclo failed: {out.stderr.strip()[:200]}")
    got = {}
    for line in out.stdout.splitlines():
        parts = line.split()
        if len(parts) < 4:
            continue
        got[parts[2]] = max(got.get(parts[2], 0), int(parts[0]))
    return got


def load():
    if not os.path.exists(BASELINE):
        return {}
    b = {}
    for line in open(BASELINE):
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        n, name = line.split(" ", 1)
        b[name] = int(n)
    return b


def write(counts):
    with open(BASELINE, "w") as f:
        f.write("# Grandfathered complexity, generated by scripts/complexity-ratchet.py.\n")
        f.write("# ⚠️ A FLOOR, NOT A TARGET. Do not add to this by hand — the ratchet\n")
        f.write("# exists so this list only ever shrinks.\n")
        for name in sorted(counts):
            f.write(f"{counts[name]} {name}\n")


def check(root=ROOT, baseline=None):
    got = measure(root)
    base = load() if baseline is None else baseline
    problems = []
    for name, n in sorted(got.items()):
        if name not in base:
            problems.append(f"NEW function over {THRESHOLD}: {name} at {n}. "
                            f"Split it, or justify it and run --update-baseline.")
        elif n > base[name]:
            problems.append(f"WORSE: {name} went {base[name]} -> {n}. The ratchet only turns down.")
    return got, base, problems


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--update-baseline", action="store_true")
    ap.add_argument("--selftest", action="store_true")
    a = ap.parse_args()

    if a.selftest:
        # A guard is not a guard until it has been shown to fail.
        print("COMPLEXITY RATCHET SELFTEST")
        got = measure()
        if not got:
            print("  ✗ measured nothing — gocyclo missing or no Go files")
            return 1
        victim = sorted(got)[0]
        _, _, p_new = check(baseline={k: v for k, v in got.items() if k != victim})
        _, _, p_worse = check(baseline={**got, victim: got[victim] - 1})
        ok = True
        if not any("NEW function" in x for x in p_new):
            print(f"  ✗ dropping {victim} from the baseline did NOT flag it as new"); ok = False
        else:
            print(f"  ✓ a new over-threshold function is caught")
        if not any("WORSE" in x for x in p_worse):
            print(f"  ✗ lowering {victim}'s baseline did NOT flag it as worse"); ok = False
        else:
            print(f"  ✓ an existing function getting worse is caught")
        _, _, p_clean = check(baseline=got)
        if p_clean:
            print(f"  ✗ an unchanged tree reported problems: {p_clean[:1]}"); ok = False
        else:
            print(f"  ✓ an unchanged tree is clean")
        print(f"\n  selftest: {'0 failures' if ok else 'FAILED'}")
        return 0 if ok else 1

    if a.update_baseline:
        got = measure()
        write(got)
        print(f"baseline written: {len(got)} function(s) over {THRESHOLD}")
        return 0

    got, base, problems = check()
    print(f"COMPLEXITY RATCHET  (threshold {THRESHOLD})")
    print(f"  {len(got)} function(s) over threshold, {len(base)} grandfathered")
    improved = [n for n in base if n in got and got[n] < base[n]] + [n for n in base if n not in got]
    if improved:
        print(f"  ✓ {len(improved)} improved since the baseline — run --update-baseline to lock it in")
    if problems:
        print("\n  PROBLEMS:")
        for p in problems:
            print(f"    ✗ {p}")
        return 1
    print("  no new complexity")
    return 0


if __name__ == "__main__":
    sys.exit(main())
