#!/usr/bin/env bash
# Regenerates the README's screenshots from the layout suite's goldens.
#
# WHY THIS EXISTS RATHER THAN A HAND-COPIED PNG
#
# docs/images/ held hand-taken shots until 2026-08-23, and by then two of the three
# were of a renderer the application no longer had — the README said so about its own
# lead image ("kept here until the shot is retaken"). A copy with no generator is one
# quantity with two implementations, and this repository has been bitten by that shape
# more than once. So the copy stays, because the goldens carry up to 34% dead page
# below the content and a README hero should not, but it is now DERIVED and one
# command refreshes it.
#
# Needs Pillow (`pip install pillow`). Byte-identical output also depends on Pillow's
# optimize=True, so a version bump can read as an image change when nothing was redrawn.
#
# The goldens themselves are regenerated by the visual suite:
#   go test ./internal/webui -run TestLayout -update
# ⚠️ Run that from a NON-HIDDEN path under $HOME. The chromium snap cannot write into
# a dot-directory and fails with a bare "Permission denied (13)" that reads like a
# broken browser.
#
# ⚠️ These shots render COMMITTED FIXTURES, not a live model run — see
# internal/webui/statefixture_test.go for why the suite was deliberately built that
# way. Caption them accordingly; they are the current planner, not this week's answer.
set -euo pipefail
cd "$(dirname "$0")/../.."
python3 - <<'PY'
from PIL import Image

# golden -> (output, bottom crop in px)
SHOTS = {
    "pitch-desktop":   ("pitch.png",   1120),
    "players-desktop": ("players.png", 1320),
    "news-desktop":    ("news.png",    1350),
}
for src, (out, bottom) in SHOTS.items():
    im = Image.open(f"internal/webui/testdata/golden/{src}.png").convert("RGB")
    w, h = im.size
    im.crop((0, 0, w, min(bottom, h))).save(f"docs/images/{out}", optimize=True)
    print(f"{src} {w}x{h} -> docs/images/{out} {w}x{min(bottom, h)}")
PY
